=== NicharNET/UNIB-4IZ236-Football-league/index.xsd
<?xml version="1.1" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	         xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" 
	         vc:minVersion="1.1"
	         elementFormDefault="qualified"
	         xmlns="https://nichar.com"
	         targetNamespace="https://nichar.com">
	
	<xsd:element name="league" type="leagueType">
		<xsd:unique name="idUnique">
			<xsd:selector xpath=".//team"/>
			<xsd:field xpath="@id"/>
		</xsd:unique>
		<xsd:unique name="nameUnique">
			<xsd:selector xpath=".//name"/>
			<xsd:field xpath="."/>
		</xsd:unique>
		<xsd:unique name="shortUnique">
			<xsd:selector xpath=".//short"/>
			<xsd:field xpath="."/>
		</xsd:unique>
		<xsd:unique name="phoneUnique">
			<xsd:selector xpath=".//phone"/>
			<xsd:field xpath="."/>
		</xsd:unique>
		<xsd:unique name="emailUnique">
			<xsd:selector xpath=".//email"/>
			<xsd:field xpath="."/>
		</xsd:unique>
	</xsd:element>

	<xsd:complexType name="leagueType">
		<xsd:sequence>
			<xsd:element name="detail" type="detailType"/>
			<xsd:element name="teams" type="teamsType"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="detailType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="director" type="directorType"/>
			<xsd:element name="season" type="xsd:positiveInteger"/>
			<xsd:element name="start" type="xsd:date"/>
			<xsd:element name="end" type="xsd:date"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="directorType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="nationality" type="nationalityType"/>
			<xsd:element name="contact" type="contactType"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="contactType">
		<xsd:sequence>
			<xsd:element name="phone" type="phoneType"/>
			<xsd:element name="email" type="emailType"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="teamsType">
		<xsd:choice minOccurs="2" maxOccurs="16">
			<xsd:element name="team" type="teamType"/>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="teamType">
		<xsd:sequence>
			<xsd:element name="description" type="descriptionType"/>
			<xsd:element name="players" type="playersType"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="idType"/>
	</xsd:complexType>

	<xsd:complexType name="descriptionType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="short" type="nationalityType"/>
			<xsd:element name="trainer" type="trainerType"/>
			<xsd:element name="stadium" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="trainerType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="nationality" type="nationalityType"/>
			<xsd:element name="licence" type="licenceType"/>
			<xsd:element name="contact" type="contactType"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="playersType">
		<xsd:choice maxOccurs="20" minOccurs="11">
			<xsd:element name="player" type="playerType"/>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="playerType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="nationality" type="nationalityType"/>
			<xsd:element name="skill" type="skillType"/>
			<xsd:element name="age" type="ageType"/>
		</xsd:sequence>
		<xsd:attribute name="position" type="positionType" use="required"/>
		<xsd:attribute name="status" type="statusType" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="skillType">
		<xsd:simpleContent>
			<xsd:extension base="skillHalfDoubleType">
				<xsd:attribute name="special" use="optional">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="free kicks"/>
							<xsd:enumeration value="quick"/>
							<xsd:enumeration value="powerful"/>
							<xsd:enumeration value="technical"/>
							<xsd:enumeration value="head"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:simpleType name="phoneType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\+00 \d{5}"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="emailType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="nationalityType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-Z]{3}"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="licenceType">
		<xsd:restriction base="xsd:NMTOKEN">
			<xsd:enumeration value="PRO"/>
			<xsd:enumeration value="A"/>
			<xsd:enumeration value="B"/>
			<xsd:enumeration value="C"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="ageType">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="15"/>
			<xsd:maxInclusive value="99"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="idType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="(0[1-9]|[1-9][0-9])"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="positionType">
		<xsd:restriction base="xsd:NMTOKEN">
			<xsd:enumeration value="goalkeeper"/>
			<xsd:enumeration value="defender"/>
			<xsd:enumeration value="midfielder"/>
			<xsd:enumeration value="forward"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="statusType">
		<xsd:restriction base="xsd:NMTOKEN">
			<xsd:enumeration value="captain"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="skillHalfDoubleType">
		<xsd:restriction base="xsd:double">
			<xsd:assertion test="$value = (for $d in 1 to 40 return 0.5 * $d)"/>
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== NicharNET/UNIB-4IZ236-Football-league/index.xml
<?xml version="1.1" encoding="UTF-8"?>
<!-- <?xml-stylesheet href="index.css" type="text/css"?> -->

<league xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
		  xmlns="https://nichar.com"
	     xsi:noNamespaceSchemaLocation="index.xsd">
	<detail>
		<name>Primero</name>
		<director>
			<name>José Manuel Rubén</name>
			<nationality>ESP</nationality>
			<contact>
				<phone>+00 16557</phone>
				<email>jm.ruben@gmail.com</email>
			</contact>
		</director>
		<season>1</season>
		<start>2016-01-01</start>
		<end>2016-12-31</end>
	</detail>
	<teams>
		<team id="01">
			<description>
				<name>Sanha</name>
				<short>SNH</short>
				<trainer>
					<name>Gina Carreiras</name>
					<nationality>ESP</nationality>
					<licence>A</licence>
					<contact>
						<phone>+00 58743</phone>
						<email>gina.carreiras@gmail.com</email>
					</contact>
				</trainer>
				<stadium>Estadio de Sanha</stadium>
			</description>
			<players>
				<player position="goalkeeper">
					<name>Alberto Carreiras</name>
					<nationality>PRT</nationality>
					<skill>7</skill>
					<age>27</age>
				</player>
				<player position="defender">
					<name>Uông Bửu Đích</name>
					<nationality>VNM</nationality>
					<skill special="technical">7.5</skill>
					<age>28</age>
				</player>
				<player position="defender" status="captain">
					<name>Francisco Calderón</name>
					<nationality>ESP</nationality>
					<skill>8.5</skill>
					<age>26</age>
				</player>
				<player position="defender">
					<name>Niccolò Azzoni</name>
					<nationality>ITA</nationality>
					<skill>7</skill>
					<age>28</age>
				</player>
				<player position="midfielder">
					<name>Feliciano Oliveira</name>
					<nationality>PRT</nationality>
					<skill>7</skill>
					<age>27</age>
				</player>
				<player position="midfielder">
					<name>Sergio Lascaris</name>
					<nationality>ESP</nationality>
					<skill special="free kicks">6.5</skill>
					<age>31</age>
				</player>
				<player position="midfielder">
					<name>Manolo Manzini</name>
					<nationality>ITA</nationality>
					<skill special="powerful">8</skill>
					<age>24</age>
				</player>
				<player position="midfielder">
					<name>Sebastien Lajoinie</name>
					<nationality>FRA</nationality>
					<skill>7</skill>
					<age>27</age>
				</player>
				<player position="midfielder">
					<name>Ciro Forestan</name>
					<nationality>ITA</nationality>
					<skill special="quick">7.5</skill>
					<age>29</age>
				</player>
				<player position="forward">
					<name>Vittorio Inzaghi</name>
					<nationality>ITA</nationality>
					<skill>8.5</skill>
					<age>26</age>
				</player>
				<player position="forward">
					<name>Juan Antonio Pintos del Valle</name>
					<nationality>ESP</nationality>
					<skill>6</skill>
					<age>35</age>
				</player>
			</players>
		</team>
		<team id="02">
			<description>
				<name>Xavao</name>
				<short>XAV</short>
				<trainer>
					<name>Hugo Odehnal</name>
					<nationality>CZE</nationality>
					<licence>B</licence>
					<contact>
						<phone>+00 56416</phone>
						<email>hugo.carreiras@outlook.com</email>
					</contact>
				</trainer>
				<stadium>Estadio de Sanha</stadium>
			</description>
			<players>
				<player position="goalkeeper">
					<name>Eriks Vārpinš</name>
					<nationality>LVA</nationality>
					<skill>6</skill>
					<age>27</age>
				</player>
				<player position="defender">
					<name>Leo Vápník</name>
					<nationality>CZE</nationality>
					<skill>6</skill>
					<age>32</age>
				</player>
				<player position="defender">
					<name>Milan Trkal</name>
					<nationality>CZE</nationality>
					<skill>6</skill>
					<age>28</age>
				</player>
				<player position="defender">
					<name>Anders Selblad</name>
					<nationality>LTU</nationality>
					<skill>7.5</skill>
					<age>25</age>
				</player>
				<player position="midfielder">
					<name>Erotas Tzolakidis</name>
					<nationality>GRC</nationality>
					<skill>7</skill>
					<age>25</age>
				</player>
				<player position="midfielder">
					<name>Sylvain von Matt</name>
					<nationality>NLD</nationality>
					<skill special="quick">6</skill>
					<age>24</age>
				</player>
				<player position="midfielder">
					<name>Milan Školník</name>
					<nationality>CZE</nationality>
					<skill special="powerful">6.5</skill>
					<age>36</age>
				</player>
				<player position="midfielder">
					<name>Alejandro González</name>
					<nationality>MEX</nationality>
					<skill special="technical">6.5</skill>
					<age>26</age>
				</player>
				<player position="forward">
					<name>Felix Krejcar</name>
					<nationality>CZE</nationality>
					<skill>6</skill>
					<age>32</age>
				</player>
				<player position="forward">
					<name>Heinrich Dörig</name>
					<nationality>DEU</nationality>
					<skill>7</skill>
					<age>36</age>
				</player>
				<player position="forward" status="captain">
					<name>Jean-Jacques Schneidewind</name>
					<nationality>CHE</nationality>
					<skill special="free kicks">6.5</skill>
					<age>34</age>
				</player>
			</players>
		</team>
		<team id="03">
			<description>
				<name>Quernera</name>
				<short>QUE</short>
				<trainer>
					<name>Manuelo Pantano</name>
					<nationality>ESP</nationality>
					<licence>A</licence>
					<contact>
						<phone>+00 56874</phone>
						<email>mpantano@outlook.com</email>
					</contact>
				</trainer>
				<stadium>Mejor Arena</stadium>
			</description>
			<players>
				<player position="goalkeeper">
					<name>Raneiro Gramatica</name>
					<nationality>ITA</nationality>
					<skill>6</skill>
					<age>22</age>
				</player>
				<player position="defender">
					<name>Michael di Bartolo</name>
					<nationality>ITA</nationality>
					<skill special="powerful">6</skill>
					<age>30</age>
				</player>
				<player position="defender">
					<name>Marcílio Teixeira</name>
					<nationality>PRT</nationality>
					<skill>6</skill>
					<age>27</age>
				</player>
				<player position="defender">
					<name>Ettore Bartoli</name>
					<nationality>ITA</nationality>
					<skill special="free kicks">7</skill>
					<age>29</age>
				</player>
				<player position="defender">
					<name>Odilson Paiva</name>
					<nationality>BRA</nationality>
					<skill special="head">5</skill>
					<age>30</age>
				</player>
				<player position="midfielder">
					<name>Giulio Scala</name>
					<nationality>DEU</nationality>
					<skill>8</skill>
					<age>28</age>
				</player>
				<player position="midfielder">
					<name>Luigino Isoardi</name>
					<nationality>ITA</nationality>
					<skill>7</skill>
					<age>32</age>
				</player>
				<player position="midfielder">
					<name>Sandalio Roa</name>
					<nationality>ESP</nationality>
					<skill special="quick">8</skill>
					<age>30</age>
				</player>
				<player position="midfielder">
					<name>Cristian Graziozo</name>
					<nationality>ITA</nationality>
					<skill>6</skill>
					<age>30</age>
				</player>
				<player position="forward" status="captain">
					<name>Ricardo Delgado</name>
					<nationality>PER</nationality>
					<skill special="technical">7</skill>
					<age>33</age>
				</player>
				<player position="forward">
					<name>Antauro Moyano</name>
					<nationality>COL</nationality>
					<skill>8.5</skill>
					<age>29</age>
				</player>
			</players>
		</team>
		<team id="04">
			<description>
				<name>Presto Pallares</name>
				<short>PRE</short>
				<trainer>
					<name>Alexandros Mousicos</name>
					<nationality>GRC</nationality>
					<licence>A</licence>
					<contact>
						<phone>+00 64158</phone>
						<email>amusica@gmail.com</email>
					</contact>
				</trainer>
				<stadium>Presto Arena</stadium>
			</description>
			<players>
				<player position="goalkeeper">
					<name>Yorgios Kalogeridis</name>
					<nationality>GRC</nationality>
					<skill>6.5</skill>
					<age>27</age>
				</player>
				<player position="defender">
					<name>Dalimil Polaković</name>
					<nationality>HRV</nationality>
					<skill special="quick">5.5</skill>
					<age>26</age>
				</player>
				<player position="defender">
					<name>Viliam Wiesner</name>
					<nationality>POL</nationality>
					<skill>5</skill>
					<age>27</age>
				</player>
				<player position="defender">
					<name>Boris van Kuppeveld</name>
					<nationality>NLD</nationality>
					<skill>6</skill>
					<age>29</age>
				</player>
				<player position="defender">
					<name>Dietmar Hüttlinger</name>
					<nationality>DEU</nationality>
					<skill special="head">5.5</skill>
					<age>30</age>
				</player>
				<player position="midfielder">
					<name>Samuel Sanchéz</name>
					<nationality>ESP</nationality>
					<skill>7</skill>
					<age>27</age>
				</player>
				<player position="midfielder">
					<name>Witek Mystek</name>
					<nationality>POL</nationality>
					<skill>5</skill>
					<age>31</age>
				</player>
				<player position="midfielder">
					<name>Marvin Warren</name>
					<nationality>USA</nationality>
					<skill>6</skill>
					<age>32</age>
				</player>
				<player position="midfielder" status="captain">
					<name>Marco Macchini</name>
					<nationality>ITA</nationality>
					<skill special="free kicks">7</skill>
					<age>27</age>
				</player>
				<player position="forward">
					<name>Massimo Fucso</name>
					<nationality>ITA</nationality>
					<skill special="technical">7.5</skill>
					<age>29</age>
				</player>
				<player position="forward">
					<name>Garry English</name>
					<nationality>GBT</nationality>
					<skill special="quick">7</skill>
					<age>28</age>
				</player>
			</players>
		</team>
		<team id="05">
			<description>
				<name>Espartinas</name>
				<short>ESP</short>
				<trainer>
					<name>Francisco Costales</name>
					<nationality>PRT</nationality>
					<licence>B</licence>
					<contact>
						<phone>+00 15645</phone>
						<email>costales-frank@gmail.com</email>
					</contact>
				</trainer>
				<stadium>Estadio de Espartinas</stadium>
